name: pocketstore
version: '0.0.0.1'
summary: A simple "Hello, World!" Go app
description: |
  A simple Go program that prints "Hello, World!" to the console.

base: core20
confinement: strict
grade: devel

apps:
  pocketstore:
    command: pocketstore    
    plugs:
      - home
      - docker
      - git-ubuntu

parts:
  pocketstore:
    plugin: go
    source: https://github.com/pocketstore-io/snapcraft.git
    source-type: git
    override-build: |
      go build -o pocketstore  # Build binary
      install -Dm755 pocketstore $SNAPCRAFT_PART_INSTALL/pocketstore