name: Build Snap for Cerbot.cloud

on: push

jobs:
  build-snap:
    runs-on: ubuntu-latest
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v3
      - name: Use Snapcraft
        run: snapcraft build